// Per-locale strings for the Sign in / Sign up flow.
// Kept separate from i18n.js so adding a new auth screen doesn't bloat the
// main translations file, and so the auth client component can import a
// small, focused module.

export const AUTH_STRINGS = {
  en: {
    signInTitle: "Welcome back",
    signUpTitle: "Create your account",
    signInSubtitle: "Sign in to use Ask AI and save your sessions.",
    signUpSubtitle: "Join HazardSignal — get personal AI briefings and stay ahead of fire risk in Antalya.",
    nameLabel: "Full name",
    namePlaceholder: "Jane Doe",
    nameHint: "How we'll greet you in the app.",
    emailLabel: "Email address",
    emailPlaceholder: "you@example.com",
    passwordLabel: "Password",
    passwordPlaceholder: "Choose a strong password",
    passwordSignInPlaceholder: "Your password",
    passwordHint: "At least 8 characters.",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordPlaceholder: "Re-enter your password",
    passwordMismatch: "Passwords don't match.",
    termsLabel: "I agree to the",
    termsLink: "Terms of Service",
    termsAnd: "and",
    privacyLink: "Privacy Policy",
    termsRequired: "Please accept the Terms of Service to continue.",
    benefitsTitle: "What you get",
    benefit1: "Unlimited Ask AI briefings (20/day)",
    benefit2: "Saved chat history across devices",
    benefit3: "Personalized district alerts (coming soon)",
    signInBtn: "Sign in",
    signUpBtn: "Create account",
    sendMagicLinkBtn: "Email me a magic link",
    googleBtn: "Continue with Google",
    or: "or",
    backToSignIn: "Back to sign in",
    needAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    forgotPassword: "Forgot your password?",
    sendingLink: "Sending link…",
    linkSent: "Check your email — we just sent you a sign-in link.",
    signingIn: "Signing in…",
    creatingAccount: "Creating account…",
    confirmEmailSent: "We sent a confirmation link to your email. Open it to finish setting up your account.",
    invalidCredentials: "Invalid email or password.",
    rateLimited: "Too many attempts. Please wait a moment and try again.",
    genericError: "Something went wrong. Please try again.",
    signOut: "Sign out",
    signedInAs: "Signed in as",
    yourAccount: "Your account"
  },
  ar: {
    signInTitle: "مرحباً بعودتك",
    signUpTitle: "أنشئ حسابك",
    signInSubtitle: "سجّل الدخول لاستخدام Ask AI وحفظ جلساتك.",
    signUpSubtitle: "انضم إلى HazardSignal — احصل على إحاطات ذكية وكن أول من يعرف عن مخاطر الحرائق في أنطاليا.",
    nameLabel: "الاسم الكامل",
    namePlaceholder: "أحمد محمد",
    nameHint: "كيف سنحييك في التطبيق.",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "you@example.com",
    passwordLabel: "كلمة المرور",
    passwordPlaceholder: "اختر كلمة مرور قوية",
    passwordSignInPlaceholder: "كلمة المرور",
    passwordHint: "8 أحرف على الأقل.",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    confirmPasswordPlaceholder: "أعد إدخال كلمة المرور",
    passwordMismatch: "كلمتا المرور غير متطابقتين.",
    termsLabel: "أوافق على",
    termsLink: "شروط الاستخدام",
    termsAnd: "و",
    privacyLink: "سياسة الخصوصية",
    termsRequired: "يرجى قبول شروط الاستخدام للمتابعة.",
    benefitsTitle: "ماذا تحصل",
    benefit1: "إحاطات Ask AI غير محدودة (20 يومياً)",
    benefit2: "سجل المحادثات يُحفظ بين الأجهزة",
    benefit3: "تنبيهات مخصّصة لمناطقك (قريباً)",
    signInBtn: "تسجيل الدخول",
    signUpBtn: "إنشاء حساب",
    sendMagicLinkBtn: "أرسل لي رابط دخول",
    googleBtn: "المتابعة عبر Google",
    or: "أو",
    backToSignIn: "العودة لتسجيل الدخول",
    needAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    forgotPassword: "نسيت كلمة المرور؟",
    sendingLink: "يتم إرسال الرابط…",
    linkSent: "تحقّق من بريدك — أرسلنا لك رابط دخول.",
    signingIn: "جاري تسجيل الدخول…",
    creatingAccount: "جاري إنشاء الحساب…",
    confirmEmailSent: "أرسلنا رابط تأكيد إلى بريدك. افتحه لإكمال إنشاء حسابك.",
    invalidCredentials: "البريد أو كلمة المرور غير صحيحة.",
    rateLimited: "محاولات كثيرة. انتظر قليلاً وحاول مرة أخرى.",
    genericError: "حدث خطأ. حاول مرة أخرى.",
    signOut: "تسجيل الخروج",
    signedInAs: "تم تسجيل الدخول باسم",
    yourAccount: "حسابك"
  },
  tr: {
    signInTitle: "Tekrar hoş geldiniz",
    signUpTitle: "Hesabınızı oluşturun",
    signInSubtitle: "Ask AI'yı kullanmak ve oturumlarınızı kaydetmek için giriş yapın.",
    signUpSubtitle: "HazardSignal'a katılın — kişisel AI özetleri alın ve Antalya'daki yangın riskinden haberdar olun.",
    nameLabel: "Ad Soyad",
    namePlaceholder: "Mehmet Yılmaz",
    nameHint: "Uygulamada size nasıl hitap edeceğiz.",
    emailLabel: "E-posta adresi",
    emailPlaceholder: "ornek@email.com",
    passwordLabel: "Şifre",
    passwordPlaceholder: "Güçlü bir şifre seçin",
    passwordSignInPlaceholder: "Şifreniz",
    passwordHint: "En az 8 karakter.",
    confirmPasswordLabel: "Şifreyi onayla",
    confirmPasswordPlaceholder: "Şifrenizi tekrar girin",
    passwordMismatch: "Şifreler eşleşmiyor.",
    termsLabel: "Şunları kabul ediyorum:",
    termsLink: "Kullanım Şartları",
    termsAnd: "ve",
    privacyLink: "Gizlilik Politikası",
    termsRequired: "Devam etmek için Kullanım Şartlarını kabul edin.",
    benefitsTitle: "Neler alacaksınız",
    benefit1: "Sınırsız Ask AI özetleri (günde 20)",
    benefit2: "Cihazlar arası kaydedilmiş sohbet geçmişi",
    benefit3: "Kişiselleştirilmiş ilçe uyarıları (yakında)",
    signInBtn: "Giriş yap",
    signUpBtn: "Hesap oluştur",
    sendMagicLinkBtn: "Bana sihirli bağlantı gönder",
    googleBtn: "Google ile devam et",
    or: "veya",
    backToSignIn: "Girişe dön",
    needAccount: "Hesabınız yok mu?",
    haveAccount: "Zaten hesabınız var mı?",
    forgotPassword: "Şifrenizi mi unuttunuz?",
    sendingLink: "Bağlantı gönderiliyor…",
    linkSent: "E-postanızı kontrol edin — size bir giriş bağlantısı gönderdik.",
    signingIn: "Giriş yapılıyor…",
    creatingAccount: "Hesap oluşturuluyor…",
    confirmEmailSent: "E-postanıza bir onay bağlantısı gönderdik. Hesabınızı kurmayı tamamlamak için açın.",
    invalidCredentials: "Geçersiz e-posta veya şifre.",
    rateLimited: "Çok fazla deneme. Lütfen biraz bekleyin ve tekrar deneyin.",
    genericError: "Bir şeyler ters gitti. Lütfen tekrar deneyin.",
    signOut: "Çıkış yap",
    signedInAs: "Giriş yapan",
    yourAccount: "Hesabınız"
  }
};

export function pickAuthStrings(locale) {
  const k = String(locale || "en").toLowerCase();
  if (k === "ar" || k === "tr") return AUTH_STRINGS[k];
  return AUTH_STRINGS.en;
}
